# Skaffold configuration file.
# Reference https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v1beta7
kind: Config
build:
  artifacts:
  - image: hello-world
deploy:
  kubectl:
    manifests:
      - k8s-*
